### ISSUE TITLE
What is going on?  as for "Instructions for fasion comming soon"

### ISSUE THREAD

**Issue by donghaoye** [AliaksandrSiarohin/pose-gan#1]
What is going on?  as for "Instructions for fasion comming soon"

**Comment by AliaksandrSiarohin** [comment]
I add the instructions, tell me if something is wrong.

**Comment by donghaoye** [comment]
I think deepfashion data should be split by persion id (id_xxxxxxx), and not the persion in clothes(yyyyidxxxxxaa).

**Comment by AliaksandrSiarohin** [comment]
So you suggest to put same person in different clothes in one bucket?
I think it is not correct. It is not possible to generate image in new cloth, given image in old cloth, because  no information about new cloth is given to the network.

**Comment by donghaoye** [comment]
In your case, some persons will in both test and train dataset.
It mixed the testing person features (face, hair, etc.. ) in the training.

**Comment by AliaksandrSiarohin** [comment]
Are you mean spiting in test and train? (I thought you mean how the pairs is created).
This you right, split in test/train should be done using person_id .
I think this is how it is done in new test/train split for fasion. Tell me if this is not the case.

**Comment by donghaoye** [comment]
the  get_id in data/split_fasion_dataset.py should be as following:
def get_id(image_path):
    path_names = image_path.split(r'/')
    path_names[-2] = path_names[-2].replace('_', '')
    #path_names[-1] = path_names[-1].split('_')[0]
    path_names[-1] =""
    return ''.join(path_names)

**Comment by AliaksandrSiarohin** [comment]
So the story is this:
Initially I write script that make wrong train/test split (This one is used in arxiv paper, and it correspond to fasion-annotations-train/test). Then I contact with authors of  https://arxiv.org/abs/1705.09368 .
And they send me their split, that I use now (This correspond to fasion-annotations-train-new-split). And this split will be used in next version of the paper.

So now I rewrite script split_fasion_dataset.py to just move the files into corresponding folders. It is not performing actual train/test split, it just move files accordingly to already existing files train-annotations-train/test (new split). If you rewrite get_id you will have problems when creating pairs_dataset.

I hope my explanation is clear.

**Comment by donghaoye** [comment]
Thanks!
I also rewrite the get_pose_name(image_path), then use the filenames of new split train/test to match the annotation file and renew the fasion-annotation-test.csv and fasion-annotation-train.csv

**Comment by AliaksandrSiarohin** [comment]
I don't understand what you mean.

**Comment by donghaoye** [comment]
I mean I will fix it by myself.

**Comment by AliaksandrSiarohin** [comment]
Ok than.
