### ISSUE TITLE
test model error

### ISSUE THREAD

**Issue by songjd** [AliaksandrSiarohin/pose-gan#11]
when I "Run python test.py --generator_checkpoint path/to/generator/checkpoint"

it errors:
ValueError: You are trying to load a weight file containing 31 layers into a model with 35 layers.

 I had tried all the models, but no one can work

**Comment by AliaksandrSiarohin** [comment]
What exact command you use?
You should specify a dataset and a warp skip, for example:

`python test.py --generator_checkpoint path/to/generator/checkpoint --warp_skip mask --dataset fashion`

But it is easier just to copy parameters from corresponding `train.py` command in `README.md`.
