### ISSUE TITLE
How should I arrange my own dataset to use your scripts for annotation and pairing?

### ISSUE THREAD

**Issue by Lotayou** [AliaksandrSiarohin/pose-gan#12]
I've finally managed to reproduce your test result, it was really amazing! I would also like to try on a different dataset and would like to use your scripts to process it, but I'm not quite sure how to arrange my dataset. Could you give me a hint? 

Specifically, I noticed that in your annotation files all images are arranged randomly, but you can create paired images for training/testing, and I'm afraid I don't quite understand how you associate one image with another? Should I specifically annotate matching image pairs (either by putting each pair in a separate folder like in DeepFashion dataset, or by giving them matching names like `img_01_train.png` and `img_01_gt.png`)?

Many thanks!

**Comment by AliaksandrSiarohin** [comment]
Imagine you want to create dataset `my`.
1) You should create folder `data/my-dataset.` With 2 sub-folders` data/my-dataset/test`
 and `data/my-dataset/train` .
2) Add your dataset in `cmd.py` line 31 and line 84.
3) Put your data into `data/my-dataset/test` and `data/my-dataset/train`. The data should have the following structure (id_person)_(id_image).jpg . The images with the same (id_person) is grouped together. Every 2 images with same (id_person) will make a pair.
4) Run `python compute_coordinates.py --dataset my` and  `python create_pairs_dataset.py --dataset my`
5) Run `train.py` and `test.py`

**Comment by Lotayou** [comment]
Thanks for the detailed guide! 

By the way, how long does it take to train a full model from scratch? My dataset is roughly the same size as fashion dataset, and the resolution is also identical (256 * 256). I use a single Nvidia Titan card with 12 GB memory.

**Comment by AliaksandrSiarohin** [comment]
It will take about 3.5 days, if you do 90k iterations of full experiment. But if you have many different persons like in fashion it can be beneficial to run for a longer time like 180k iterations.

**Comment by Lotayou** [comment]
Thanks for the info!
