### ISSUE TITLE
input_1:0 is both fed and fetched.

### ISSUE THREAD

**Issue by dimaxano** [AliaksandrSiarohin/pose-gan#15]
I'm running this command 

`CUDA_VISIBLE_DEVICES=0 test.py --generator_checkpoint checkpoints/market/generator-no-warp.h5 --warp_skip none --dataset market`

But I'm getting error

`input_1:0 is both fed and fetched`

tf==1.11.0
keras==2.2.3

Is there any ideas of how to solve it?

**Comment by AliaksandrSiarohin** [comment]
It seems like in new tensorflow you can not return the input. You can alternatively try (in line 142 conditional_gan.py) 
```
outputs = [input_img] + input_pose + [out, output_pose] + bg_img + warp_in_disc
outputs = [keras.layers.Lambda(lambda x: ktf.identity(x))(out) for out in outputs]
```
I did not try this, so no idea if it works or no.
So the simplest way would be to install the version I use:
I use: tf==r1.3, keras==2.0.8

**Comment by dimaxano** [comment]
That works for me! Thank you!
