### ISSUE TITLE
[Bug Found]: compute_st_distance will crash for incomplete input skeletons

### ISSUE THREAD

**Issue by Lotayou** [AliaksandrSiarohin/pose-gan#19]
@AliaksandrSiarohin I'm running a test with pre-trained model, but encountered the following error:

Traceback (most recent call last):
  File "test_video.py", line 121, in <module>
    test(1)
  File "test_video.py", line 99, in test
    out = generate_video(video, pose, generator)
  File "test_video.py", line 75, in generate_video
    batch = prepare_batch(src_frame, frame, src_skeleton, skeleton)
  File "test_video.py", line 57, in prepare_batch
    result += [pose_transform.affine_transforms(pose_from, pose_to)]
  File "/backup/lingboyang/pose-gan/pose_transform.py", line 199, in affine_transforms
    st2 = compute_st_distance(kp2)
  File "/backup/lingboyang/pose-gan/pose_transform.py", line 103, in compute_st_distance
    st_distance2 = np.sum((kp['Lhip'] - kp['Lsho']) ** 2)
KeyError: 'Lsho'

And here's where the error take place: In pose_transform.py around line 100:
```
def compute_st_distance(kp):
    st_distance1 = np.sum((kp['Rhip'] - kp['Rsho']) ** 2)
    st_distance2 = np.sum((kp['Lhip'] - kp['Lsho']) ** 2)
    return np.sqrt((st_distance1 + st_distance2)/2.0)
```

By checking missing keys in kp I found the problematic frame with pose and skeletons:
```
array([[ 25, 113],
       [ 53, 122],
       [ 53, 107],
       [ 85,  88],
       [110,  59],
       [ -1,  -1],
       [ -1,  -1],
       [ -1,  -1],
       [129, 110],
       [177, 108],
       [233, 108],
       [128, 138],
       [176, 151],
       [223, 168],
       [ 19, 108],
       [ 19, 119],
       [ 24, 105],
       [ 25, 130]], dtype=int32)

```

Do you think it's okay to use the distance between neck and both hips? It seems the neck point are more stable than shoulder points.

**Comment by AliaksandrSiarohin** [comment]
As explained in the paper we remove the data where the key-point detector is not able to extract a body (More specifically 4 keypoint 'Lhip', 'Lsho', 'Rhip', 'Rsho'). Check ```create_pairs_dataset.py```.
So the ```pose_transform.py``` file is written, given the assumption that all this 4 keypoints is present. 
That is why I use only this 4 keypoints for estimating the distance.

But you are right, the code is suboptimal in many ways. And maybe using the distance between a neck and a shoulders is better.

**Comment by Lotayou** [comment]
Thanks for the explanation. It seems I forgot to clean the input data.
