### ISSUE TITLE
What the number of  epoch in your last vision paper?

### ISSUE THREAD

**Issue by donghaoye** [AliaksandrSiarohin/pose-gan#2]
Hi,
What the number of your last vision paper?
90 epoch or 500 epoch?

**Comment by AliaksandrSiarohin** [comment]
90. Parameters is the same as in README.md

**Comment by donghaoye** [comment]
Thanks!
I'm confused about 1000 iterations per epoch. 
Why don't you choose all iterations(about 8w)? 
Is it helpful to accelerate the training?

**Comment by AliaksandrSiarohin** [comment]
1000 iterations per epoch is just cosmetic.
Gan submodule show scores once per epoch. I cant wait 8w(what does it mean?)  to see the scores.
It does not affect anything besides this.

**Comment by donghaoye** [comment]
8w means that there are about 80,000 pairs image in your train data, therefore it should be included 80,000 iterations in per epoch.

**Comment by AliaksandrSiarohin** [comment]
As I told this has a cosmetic effect only. Following your logic, there should be 80,000 / batch_size iterations, but whatever. Probably source of you confusion is the fact that I only do about 2 passes through data. This is true, I have limited gpu resources, and I never try to use more iterations for fasion. Most probably more iterations can help to improve the performance.

**Comment by donghaoye** [comment]
It means that one epoch = one forward pass and one backward pass of all the training examples.
But in your code, you only chose the 1000 batches per epoch.

**Comment by AliaksandrSiarohin** [comment]
You can make a fork, and set whatever batches you want.
As I told it is not affect anything.

**Comment by donghaoye** [comment]
I get it, Thank you very much.
