### ISSUE TITLE
About body mask

### ISSUE THREAD

**Issue by lijiaqi** [AliaksandrSiarohin/pose-gan#20]
Hi Aliaksandr,
Thanks for your work and code. I have a question about one of the ten masks: torso mask.
In your implementation in `def pose_masks(array2, img_size):`:
https://github.com/AliaksandrSiarohin/pose-gan/blob/13ca2720501951da449aea2b1cec7d86a57a67b7/pose_transform.py#L131

According to my understanding, this line aims to obtain the mask for torso, why do you use a full-one mask rather than a mask obtained by the method you commented `mask_from_kp_array(...)` ?

**Comment by AliaksandrSiarohin** [comment]
Hi Jiaqi,
Simple answer that this works better.
In more details this helps with missing detections. Take a look for example to first image row in README.md . The legs of the girl is not detected, consequently there will be no masks specifically for the legs. But we can aproximate the transformation for the legs using the body(we assume that it always present). The easiest way to achieve this is to  assume, that mask for a body is full image.

**Comment by lijiaqi** [comment]
I see. Thanks for your reply.
