### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by SheelaRaju** [AliaksandrSiarohin/pose-gan#24]
Hello 

When I try running "compute_coordinates.py" I get the following Attribute error. 

File "compute_coordinates.py", line 1, in <module>
    import pose_utils
  File "/mocapdata/Students/sheela/pose-gan/pose_utils.py", line 3, in <module>
    from skimage.draw import circle, line_aa, polygon
  File "/mocapdata/Students/sheela/env/local/lib/python2.7/site-packages/skimage/__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "/mocapdata/Students/sheela/env/local/lib/python2.7/site-packages/skimage/util/__init__.py", line 6, in <module>
    from .apply_parallel import apply_parallel
  File "/mocapdata/Students/sheela/env/local/lib/python2.7/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/mocapdata/Students/sheela/env/local/lib/python2.7/site-packages/dask/array/__init__.py", line 9, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/mocapdata/Students/sheela/env/local/lib/python2.7/site-packages/dask/array/routines.py", line 256, in <module>
    @wraps(np.matmul)
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'

Could you please let me know what is the problem? How can it be solved?

Thanks

**Comment by AliaksandrSiarohin** [comment]
Seems the problem is in you libraries:
If you run, just:
```
from skimage.draw import circle, line_aa, polygon
```
in python console, do you see the same error?
You can also check the tread: https://stackoverflow.com/questions/54232495/attributeerror-numpy-ufunc-object-has-no-attribute-module

**Comment by SheelaRaju** [comment]
Hello,

Thank you so much. It solved my problem.

Thanks
Sheela

**Comment by SheelaRaju** [comment]
Hello,

Could you please tell me the versions of libraries that 
you are using.

Numpy
Scipy
Skimage
Pandas
Tensorflow
Keras
Keras-contrib
tqdm

Thanks
Sheela

**Comment by AliaksandrSiarohin** [comment]
Hi, 
I add the file with versions https://github.com/AliaksandrSiarohin/pose-gan/blob/master/requirements.txt

**Comment by SheelaRaju** [comment]
Thank you so much. I found an argument --pose_rep_type 
with hm or stick-pose values. Does changing these values 
change the intermediate representation?
Would it benefit training by using pose-stick figures.

**Comment by AliaksandrSiarohin** [comment]
hm is representation of the pose as described in my paper. (18 - channels gaussian heatmaps)
stickman is representation of a pose like in this paper https://compvis.github.io/vunet/images/vunet.pdf, (Stick-man like images RGB images)
Visually I did not observe any difference between these.

**Comment by SheelaRaju** [comment]
I got the following error when I ran testing:

ValueError: Cannot feed value of shape (10, 128, 64, 3) 
for Tensor u'ExpandDims:0', which has shape '(1, ?, ?, 3)'

How could I resolve this ? Do I need to change the version 
of tensorflow?

**Comment by AliaksandrSiarohin** [comment]
Please provide full stack trace.

**Comment by AliaksandrSiarohin** [comment]
And the precise command you use to launch.
