### ISSUE TITLE
Question: Resource requirements

### ISSUE THREAD

**Issue by gayashanbc** [AliaksandrSiarohin/pose-gan#25]
What are the average hardware requirements (i.e. GPU, Memory, Disk space), in order to train and test this model?

**Comment by AliaksandrSiarohin** [comment]
Don't remember exactly, something like:
Market:
Time: 22h
GPU-mem: 3-5GB
Disk: ~50GB
Fashion:
Time: 3-4 days
GPU-mem: 11-12GB
Disk: ~150GB

**Comment by gayashanbc** [comment]
OK, thanks 😄
