### ISSUE TITLE
Problem about skimage_transfrom

### ISSUE THREAD

**Issue by OwalnutO** [AliaksandrSiarohin/pose-gan#29]
Hi, a warning is proposed during the first epoch training,

/home/tj/.conda/envs/dsc/lib/python3.6/site-packages/skimage/transform/_geometric.py:683: RuntimeWarning: divide by zero encountered in true_divide
  H.flat[list(self._coeffs) + [8]] = - V[-1, :-1] / V[-1, -1]

It seems that when calculating the transformation matrix, for some samples, there will have zeros in division. It may not influence the training process, but does anyone know why or in which case (what kind of skeleton pair) this warning occurs?

**Comment by AliaksandrSiarohin** [comment]
You can ignore it. I think, it occurs when 2 keypoints have exactly the same location.
