### ISSUE TITLE
However, results performed not as well as in your current version paper. 

### ISSUE THREAD

**Issue by donghaoye** [AliaksandrSiarohin/pose-gan#3]
I select the following person_id as test data, which were also used in "pose_guided" and "Disentangled Person Image Generation", and the run train.py and test.py

CUDA_VISIBLE_DEVICES=0 python train.py --output_dir output/full --checkpoints_dir output/full --warp_skip mask --dataset fasion --l1_penalty_weight 0.01 --nn_loss_area_size 5 --batch_size 2 --content_loss_layer block1_conv2 --number_of_epochs 90

CUDA_VISIBLE_DEVICES=3 python test.py --generator_checkpoint output/full/epoch_089_generator.h5 --warp_skip mask --dataset fasion --l1_penalty_weight 0.01 --nn_loss_area_size 5 --batch_size 2 --content_loss_layer block1_conv2

 However, results performed not as well as in your current version paper. (and same parameters as in train.py)

SSIM score masked 0.9499144956871529 Inception score = (3.2932858, 0.039500084),masked = (3.5532665, 0.09156021);
SSIM score = 0.7542003027263708, masked = 0.9499144956871529;l1 score = 0.12546359778842633

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000350408_3back.jpg_fasionWOMENTeesTanksid0000350408_1front.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000350408_3back.jpg_fasionWOMENTeesTanksid0000350408_1front.jpg.png)

![](http://47.100.21.47/image/fasionWOMENBlousesShirtsid0000210701_2side.jpg_fasionWOMENBlousesShirtsid0000210701_3back.jpg.png)
(http://47.100.21.47/image/fasionWOMENBlousesShirtsid0000210701_2side.jpg_fasionWOMENBlousesShirtsid0000210701_3back.jpg.png)

![](http://47.100.21.47/image/fasionWOMENCardigansid0000369601_2side.jpg_fasionWOMENCardigansid0000369601_1front.jpg.png)
(http://47.100.21.47/image/fasionWOMENCardigansid0000369601_2side.jpg_fasionWOMENCardigansid0000369601_1front.jpg.png)

![](http://47.100.21.47/image/fasionWOMENCardigansid0000369601_4full.jpg_fasionWOMENCardigansid0000369601_2side.jpg.png)
(http://47.100.21.47/image/fasionWOMENCardigansid0000369601_4full.jpg_fasionWOMENCardigansid0000369601_2side.jpg.png)

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000121234_1front.jpg_fasionWOMENTeesTanksid0000121234_2side.jpg.png)

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000121234_3back.jpg_fasionWOMENTeesTanksid0000121234_1front.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000121234_3back.jpg_fasionWOMENTeesTanksid0000121234_1front.jpg.png)

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000121234_3back.jpg_fasionWOMENTeesTanksid0000121234_2side.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000121234_3back.jpg_fasionWOMENTeesTanksid0000121234_2side.jpg.png)

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_2side.jpg_fasionWOMENTeesTanksid0000131001_1front.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_2side.jpg_fasionWOMENTeesTanksid0000131001_1front.jpg.png)

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_7additional.jpg_fasionWOMENTeesTanksid0000131001_3back.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_7additional.jpg_fasionWOMENTeesTanksid0000131001_3back.jpg.png)

id_00005363
id_00006364
id_00004600
id_00006814
id_00002068
id_00005364
id_00007540
id_00007542
id_00005361
id_00005152
id_00007466
id_00006569
id_00003907
id_00002591
id_00005486
id_00004703
id_00004469
id_00004701
id_00005482
id_00006817
id_00005762
id_00005761
id_00005316
id_00005317
id_00005310
id_00006965
id_00001184
id_00002112
id_00002114
id_00005318
id_00001140
id_00004991
id_00005466
id_00007383
id_00007382
id_00006311
id_00006317
id_00006315
id_00007384
id_00006318
id_00004840
id_00000814
id_00007261
id_00004963
id_00006498
id_00006499
id_00005162
id_00006782
id_00005168
id_00000099
id_00004260
id_00004566
id_00001249
id_00007017
id_00000666
id_00004560
id_00002300
id_00006084
id_00000782
id_00001368
id_00005189
id_00006147
id_00005180
id_00002597
id_00003285
id_00006223
id_00006222
id_00003168
id_00001393
id_00007314
id_00000164
id_00000862
id_00001783
id_00001629
id_00001784
id_00005263
id_00007721
id_00007723
id_00000561
id_00000160
id_00007729
id_00001566
id_00003576
id_00000928
id_00005986
id_00004103
id_00000271
id_00001764
id_00004294
id_00006139
id_00004290
id_00000969
id_00006132
id_00004299
id_00006135
id_00002365
id_00003767
id_00003602
id_00007926
id_00000140
id_00007436
id_00007920
id_00000438
id_00003418
id_00002415
id_00007426
id_00006526
id_00007425
id_00006520
id_00002960
id_00002962
id_00003788
id_00000048
id_00007032
id_00004030
id_00002969
id_00004033
id_00004035
id_00005918
id_00005910
id_00005911
id_00004583
id_00003466
id_00002566
id_00002560
id_00002561
id_00003460
id_00005421
id_00006357
id_00001069
id_00002732
id_00006982
id_00003534
id_00002446
id_00007452
id_00007451
id_00007450
id_00007454
id_00004633
id_00004630
id_00005619
id_00004921
id_00004736
id_00005617
id_00005737
id_00005327
id_00006855
id_00005325
id_00006851
id_00006188
id_00005253
id_00001615
id_00001203
id_00006180
id_00005557
id_00007468
id_00006677
id_00001511
id_00006678
id_00001145
id_00001973
id_00003006
id_00001925
id_00003002
id_00007694
id_00004952
id_00001844
id_00005137
id_00000135
id_00001339
id_00007972
id_00007602
id_00000132
id_00003185
id_00007703
id_00001334
id_00007609
id_00001724
id_00004256
id_00006077
id_00001728
id_00006177
id_00000623
id_00003523
id_00001923
id_00003649
id_00003456
id_00002929
id_00007076
id_00000553
id_00004783
id_00003824
id_00007771
id_00003822
id_00007777
id_00003458
id_00007670
id_00001430
id_00004173
id_00003311
id_00002191
id_00005955
id_00006009
id_00007730
id_00005815
id_00005814
id_00002353
id_00002605
id_00002356
id_00000950
id_00003732
id_00000488
id_00000521
id_00007808
id_00007982
id_00002628
id_00007552
id_00007807
id_00007417
id_00001890
id_00000319
id_00006550
id_00003914
id_00004677
id_00004675
id_00002995
id_00003856
id_00004478
id_00007786
id_00007782
id_00001779
id_00005775
id_00004472
id_00004778
id_00007895
id_00002107
id_00007899
id_00007508
id_00006739
id_00006803
id_00001155
id_00001093
id_00001094
id_00001097
id_00007258
id_00007398
id_00000131
id_00004855
id_00004853
id_00005587
id_00001807
id_00007159
id_00001801
id_00005177
id_00001135
id_00001028
id_00002771
id_00001027
id_00002774
id_00005071
id_00001371
id_00000775
id_00007286
id_00005204
id_00003660
id_00007130
id_00006607
id_00006606
id_00006602
id_00005693
id_00003212
id_00007322
id_00000706
id_00000871
id_00005291
id_00000702
id_00003073
id_00001791
id_00001652
id_00002384
id_00003315
id_00002381
id_00001578
id_00002383
id_00003254
id_00003257
id_00007634
id_00003318
id_00001570
id_00001571
id_00001477
id_00005858
id_00001474
id_00004509
id_00001774
id_00000150
id_00002256
id_00002257
id_00000239
id_00006043
id_00003389
id_00002315
id_00006125
id_00002258
id_00003776
id_00000678
id_00000172
id_00003676
id_00001687
id_00004180
id_00007931
id_00004183
id_00007844
id_00002131
id_00007022
id_00003957
id_00007026
id_00001508
id_00002951
id_00003790
id_00001501
id_00000196
id_00000195
id_00004002
id_00007013
id_00004430
id_00003672
id_00003493
id_00002552
id_00002226
id_00000459
id_00002558
id_00001485
id_00002655
id_00001055
id_00005021
id_00005799
id_00007118
id_00006585
id_00006581
id_00004641
id_00004640
id_00003644
id_00004649
id_00007109
id_00005704
id_00006863
id_00007599
id_00005702
id_00005335
id_00006900
id_00002035
id_00005709
id_00007595
id_00007678
id_00007043
id_00001495
id_00006642
id_00006644
id_00003913
id_00004328
id_00006769
id_00007365
id_00005093
id_00001289
id_00001282
id_00004860
id_00003132
id_00003814
id_00004946
id_00001114
id_00000603
id_00001116
id_00005412
id_00005417
id_00005416
id_00003620
id_00003623
id_00001446
id_00003581
id_00001396
id_00003585
id_00004543
id_00000193
id_00004267
id_00005896
id_00004261
id_00005890
id_00004389
id_00004386
id_00004385
id_00004269
id_00001739
id_00004380
id_00006425
id_00006163
id_00006247
id_00006242
id_00001943
id_00001230
id_00002662
id_00003446
id_00002912
id_00000390
id_00007708
id_00000017
id_00003361
id_00003449
id_00007701
id_00007661
id_00007662
id_00005963
id_00003696
id_00005801
id_00000006
id_00005804
id_00002263
id_00001627
id_00003219
id_00002617
id_00000512
id_00000122
id_00000120
id_00000121
id_00000124
id_00003216
id_00006421
id_00007839
id_00007838
id_00006426
id_00006542
id_00002162
id_00002163
id_00000560
id_00007404
id_00004682
id_00003964
id_00001882
id_00003962
id_00007015
id_00000065
id_00002223
id_00007797
id_00006728
id_00004804
id_00002460
id_00006942
id_00007498
id_00007888
id_00002503
id_00004816
id_00003996
id_00007178
id_00006687
id_00005115
id_00006683
id_00006682
id_00002713
id_00006727
id_00006722
id_00002715
id_00002714
id_00006334
id_00006336
id_00007246
id_00007531
id_00007089
id_00007125
id_00003498
id_00007121
id_00004611
id_00007082
id_00004907
id_00004615
id_00001011
id_00002228
id_00002198
id_00005066
id_00002763
id_00005062
id_00004348
id_00004349
id_00004889
id_00004885
id_00001268
id_00004341
id_00005231
id_00003235
id_00003099
id_00006616
id_00004485
id_00003140
id_00007331
id_00007334
id_00003060
id_00007235
id_00001868
id_00001903
id_00001902
id_00001863
id_00001866
id_00000112
id_00000506
id_00005382
id_00007629
id_00004083
id_00003719
id_00000119
id_00002606
id_00005866
id_00004120
id_00004533
id_00000982
id_00003398
id_00002309
id_00002304
id_00003396
id_00000593
id_00003196
id_00000532
id_00007901
id_00007903
id_00007904
id_00007907
id_00000161
id_00001345
id_00000168
id_00006506
id_00007065
id_00002822
id_00002121
id_00002941
id_00003431
id_00005888
id_00000341
id_00004012
id_00004159
id_00007753
id_00003801
id_00003802
id_00004400
id_00001512
id_00007695
id_00004156
id_00004155
id_00000187
id_00005624
id_00005831
id_00007195
id_00007589
id_00002541
id_00000935
id_00002239
id_00000936
id_00003325
id_00000932
id_00005015
id_00006802
id_00006800
id_00006375
id_00002050
id_00007804
id_00005395
id_00005019
id_00006477
id_00006577
id_00000235
id_00007477
id_00003933
id_00002334
id_00005496
id_00005713
id_00004716
id_00004711
id_00006837
id_00006926
id_00005657
id_00001895
id_00002431
id_00007875
id_00003917
id_00001634
id_00005479
id_00004305
id_00004303
id_00006658
id_00006659
id_00006657
id_00005476
id_00004309
id_00006898
id_00006899
id_00005085
id_00007371
id_00007277
id_00006486
id_00006483
id_00000804
id_00007271
id_00004873
id_00004975
id_00001825
id_00004976
id_00004971
id_00001127
id_00001044
id_00001709
id_00001310
id_00000288
id_00003610
id_00000659
id_00001705
id_00001254
id_00006091
id_00006257
id_00003304
id_00003298
id_00007301
id_00003116
id_00003114
id_00001384
id_00007036
id_00003504
id_00007302
id_00000727
id_00006391
id_00002673
id_00003376
id_00002675
id_00002678
id_00003378
id_00007717
id_00002522
id_00007654
id_00001553
id_00001415
id_00001559
id_00004118
id_00003353
id_00000978
id_00000840
id_00003052
id_00000971
id_00000973
id_00004289
id_00007958
id_00000159
id_00007950
id_00003753
id_00006920
id_00007820
id_00002010
id_00006539
id_00002154
id_00002157
id_00007432
id_00006532
id_00002153
id_00006530
id_00003974
id_00002972
id_00004029
id_00002931
id_00004021
id_00003344
id_00003870
id_00000550
id_00005757
id_00002089
id_00004593
id_00004459
id_00003479
id_00003470
id_00000380
id_00007487
id_00005124
id_00000396
id_00005515
id_00006322
id_00002703
id_00007752
id_00005478
id_00003278
id_00003064
id_00006994
id_00006991
id_00006990
id_00005106
id_00004931
id_00004935
id_00004626
id_00005723
id_00005720
id_00006849
id_00005357
id_00001008
id_00001649
id_00004236
id_00004234
id_00005548
id_00001212
id_00003082
id_00005305
id_00004330
id_00006196
id_00006737
id_00000342
id_00006199
id_00007344
id_00003152
id_00007391
id_00007221
id_00000850
id_00007223
id_00001671
id_00001915
id_00004803
id_00001678
id_00001856
id_00005532
id_00001919
id_00001590
id_00001592
id_00003233
id_00007966
id_00004489
id_00001455
id_00001326
id_00004243
id_00005976
id_00003241
id_00001755
id_00006060
id_00006062
id_00001696
id_00001585
id_00006264
id_00003123
id_00007914
id_00003127
id_00007910
id_00003658
id_00000079
id_00003551
id_00003557
id_00007918
id_00002836
id_00003423
id_00002834
id_00002523
id_00003424
id_00005876
id_00003343
id_00003340
id_00003345
id_00007621
id_00004067
id_00003628
id_00004419
id_00007684
id_00000038
id_00004798
id_00007157
id_00006450
id_00005945
id_00003887
id_00001163
id_00000917
id_00002201
id_00002203
id_00003336
id_00004090
id_00001113
id_00003883

**Comment by AliaksandrSiarohin** [comment]
How many pairs you have in fasion-pairs-train,  fasion-pairs-test?
I have the following scores 
IS|SSIM|MASK_IS|MASK_SSIM|DS
3.4393044 | 0.7557447987 | 3.5854161 | 0.9469704733 | 0.9624735183
(But I have to say this scores means more or less nothing).

Also only one pair that you show is matched present in a paper. (http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_2side.jpg_fasionWOMENTeesTanksid0000131001_1front.jpg.png). And it look more or less similar to what I have.

**Comment by donghaoye** [comment]
fasion-pairs-train: 86089 pairs
fasion-pairs-test:  12000 pairs

May I have the person_id in your ablation study?

![](http://47.100.21.47/image/fasionMENShirtsPolosid0000541703_4full.jpg_fasionMENShirtsPolosid0000541703_1front.jpg.png)
(http://47.100.21.47/image/fasionMENShirtsPolosid0000541703_4full.jpg_fasionMENShirtsPolosid0000541703_1front.jpg.png)

![](http://47.100.21.47/image/fasionMENTeesTanksid0000730105_3back.jpg_fasionMENTeesTanksid0000730105_1front.jpg.png)
(http://47.100.21.47/image/fasionMENTeesTanksid0000730105_3back.jpg_fasionMENTeesTanksid0000730105_1front.jpg.png)


![](http://47.100.21.47/image/fasionWOMENBlousesShirtsid0000210701_2side.jpg_fasionWOMENBlousesShirtsid0000210701_3back.jpg.png)
(http://47.100.21.47/image/fasionWOMENBlousesShirtsid0000210701_2side.jpg_fasionWOMENBlousesShirtsid0000210701_3back.jpg.png)

![](http://47.100.21.47/image/fasionWOMENDressesid0000759902_3back.jpg_fasionWOMENDressesid0000759902_7additional.jpg.png)
(http://47.100.21.47/image/fasionWOMENDressesid0000759902_3back.jpg_fasionWOMENDressesid0000759902_7additional.jpg.png)


![](http://47.100.21.47/image/fasionWOMENSweatersid0000703205_2side.jpg_fasionWOMENSweatersid0000703205_4full.jpg.png)
(http://47.100.21.47/image/fasionWOMENSweatersid0000703205_2side.jpg_fasionWOMENSweatersid0000703205_4full.jpg.png)

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_3back.jpg_fasionWOMENTeesTanksid0000131001_1front.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_3back.jpg_fasionWOMENTeesTanksid0000131001_1front.jpg.png)


![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000121234_2side.jpg_fasionWOMENTeesTanksid0000121234_1front.jpg.png)
(http://47.100.21.47/image/)

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000350408_3back.jpg_fasionWOMENTeesTanksid0000350408_1front.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000350408_3back.jpg_fasionWOMENTeesTanksid0000350408_1front.jpg.png)

![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000121234_1front.jpg_fasionWOMENTeesTanksid0000121234_2side.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000121234_1front.jpg_fasionWOMENTeesTanksid0000121234_2side.jpg.png)



![](http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_7additional.jpg_fasionWOMENTeesTanksid0000131001_3back.jpg.png)
(http://47.100.21.47/image/fasionWOMENTeesTanksid0000131001_7additional.jpg_fasionWOMENTeesTanksid0000131001_3back.jpg.png)

**Comment by AliaksandrSiarohin** [comment]
To me same pairs, looks similar to what is reported in the paper.
The pairs in ablation taken from an old split. File names is this:
fasionMENTeesTanksid0000774801_4full.jpg_fasionMENTeesTanksid0000774801_3back.jpg.png
fasionWOMENGraphicTeesid0000485302_1front.jpg_fasionWOMENGraphicTeesid0000485302_7additional.jpg.png
fasionWOMENCardigansid0000233702_3back.jpg_fasionWOMENCardigansid0000233702_1front.jpg.png
fasionWOMENBlousesShirtsid0000298301_3back.jpg_fasionWOMENBlousesShirtsid0000298301_1front.jpg.png
fasionWOMENBlousesShirtsid0000277201_3back.jpg_fasionWOMENBlousesShirtsid0000277201_1front.jpg.png
fasionWOMENBlousesShirtsid0000179002_1front.jpg_fasionWOMENBlousesShirtsid0000179002_4full.jpg.png

**Comment by donghaoye** [comment]
Thank you!
Could you tell which conference did you submit?

**Comment by AliaksandrSiarohin** [comment]
CVPR

**Comment by donghaoye** [comment]
Hi, did this paper accept in cvpr2018?
