### ISSUE TITLE
improve training

### ISSUE THREAD

**Issue by SheelaRaju** [AliaksandrSiarohin/pose-gan#30]
I have trained the network and see that the texture information is not generated properly and it is blurry. I would like to know for how many epochs did you train the model. What could be still changed to improve the generated images.

**Comment by AliaksandrSiarohin** [comment]
The number if epochs is 90, for fashion it is probably better to train for longer time. Are you using the this command:
```
CUDA_VISIBLE_DEVICES=0 python train.py --output_dir output/full --checkpoints_dir output/full --warp_skip mask --dataset fasion --l1_penalty_weight 0.01 --nn_loss_area_size 5 --batch_size 2 --content_loss_layer block1_conv2 --number_of_epochs 90
```

**Comment by SheelaRaju** [comment]
Yes I am using the same command. How could the training be improved other than training for longer time.

**Comment by AliaksandrSiarohin** [comment]
If I know how to significantly improve the performance I would probably do that. Some improvement can be probably obtained by using better HPE model (e.g Mask RCNN), better discriminator (for example discriminator with Spectral Normalization) and by incorporation perceptual and feature matchings losses (from pix2pixHD model).

**Comment by lijiaqi** [comment]
@AliaksandrSiarohin What is your opinion about the improvement by replacing vanilla GAN loss with WGAN loss ? From my experiences, may be it improves the results in noise-based image generation, but it seems it brings only limited improvements in image translation task, or even no. How do you think about this opinion?

**Comment by AliaksandrSiarohin** [comment]
I personally trust more in hinge loss with spectral normalization for generation from noise. But for image to image translation I do not think you observe some big difference by changing only the GAN loss.  I believe that a main driving component in image2image is reconstruction loss. So the main benefits comes from  better generator architecture and better design of this reconstruction loss.

**Comment by lijiaqi** [comment]
@AliaksandrSiarohin yep, it's the reconstruction loss that dominates img2img generation results.
