### ISSUE TITLE
Annotation result on my own dataset

### ISSUE THREAD

**Issue by zwbzwj123** [AliaksandrSiarohin/pose-gan#31]
> Imagine you want to create dataset `my`.
> 
> 1. You should create folder `data/my-dataset.` With 2 sub-folders` data/my-dataset/test`
>    and `data/my-dataset/train` .
> 2. Add your dataset in `cmd.py` line 31 and line 84.
> 3. Put your data into `data/my-dataset/test` and `data/my-dataset/train`. The data should have the following structure (id_person)_(id_image).jpg . The images with the same (id_person) is grouped together. Every 2 images with same (id_person) will make a pair.
> 4. Run `python compute_coordinates.py --dataset my` and  `python create_pairs_dataset.py --dataset my`
> 5. Run `train.py` and `test.py`

Hi, 

I just run compute_coordinates.py as the steps, and I got the annotation files. But the values in the file my-annotation-test.csv are all -1. What's the matter?

`name:keypoints_y:keypoints_x
0188_c2s2_149727_03.jpg: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
0467_c1s2_049246_04.jpg: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
0501_c3s1_136908_05.jpg: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]`

**Comment by zhaomeihu** [comment]
Hi, have you solved this problem? I met the same problem. Could you help me ?

**Comment by AliaksandrSiarohin** [comment]
This most likely means that human pose estimator can not detect any human.
