### ISSUE TITLE
Is it possible to transpose person's pose?

### ISSUE THREAD

**Issue by dajinstory** [AliaksandrSiarohin/pose-gan#35]
I want to use pose-gan in this way.

1. input two images(image1 and image2).
2. image1 has a person A taking a pose X.
image 2 has a person B taking a pose Y
3. i want my output would be a person A taking a pose Y

But, i read the paper and it was quite different from what i thought......
In paper, two input images must have same person. just with different pose.

Do you think i can get the result what i want?

Sorry for asking too personal questions..

**Comment by AliaksandrSiarohin** [comment]
It is possible. The method works similarly to others: first you extract the pose in term of a keypoints Y. Then you combine this pose Y and appearance A using GAN. In paper images of the same person show for comparison with ground truth. You can youse ```demo.py``` for this.

**Comment by dajinstory** [comment]
Thanks for quick answer!    :)
The same person in both input images  is just for training.
