### ISSUE TITLE
Error while executing create_pairs_dataset.py

### ISSUE THREAD

**Issue by Seairis7** [AliaksandrSiarohin/pose-gan#42]
File "/home/abc/Desktop/pose-gan/pose_transform.py", line 3, in <module>
    from keras.backend import tf as ktf
ImportError: cannot import name tf

**Comment by AliaksandrSiarohin** [comment]
Do you have tensorflow installed?

**Comment by Seairis7** [comment]
@AliaksandrSiarohin  yes i have installed tensorflow 1.14.0

**Comment by AliaksandrSiarohin** [comment]
Guess you would require 2.0.8 keras anyway. But you can change this line to:
import tensorflow as ktf

**Comment by Seairis7** [comment]
@AliaksandrSiarohin  while i start train in dsc it says:: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ? 
what is the problem here??

**Comment by AliaksandrSiarohin** [comment]
Version problem most likely.
I use keras=2.0.8, and tensorflow=1.5
