### ISSUE TITLE
Create fasion annotation and pairing fasion data

### ISSUE THREAD

**Issue by Seairis7** [AliaksandrSiarohin/pose-gan#44]
How to compute keypoints  coordinate of fasion data and create pairs??

**Comment by AliaksandrSiarohin** [comment]
You can download keypoint annotations (https://yadi.sk/d/suymftBy3S7oKD) or run
```
python compute_cordinates.py --dataset fashion
```
Same for pairs, just add  --dataset fashion

**Comment by Seairis7** [comment]
@AliaksandrSiarohin Thank you for your response and i have few more questions if you will fell free to answer 
Q1: Why is train part  divided into baseline, dsc, full, and feature matching??
Q2 : How to save trained model after each epoch?
Q3: How to train data of slightly high resolution?
Q4: Where should i keep the downloaded checkpoints for testing??

**Comment by AliaksandrSiarohin** [comment]
Q1:
This is all different baseline methods. (see https://arxiv.org/pdf/1801.00055.pdf Table.3)
Q2: 
You can specify ```--checkpoint_ratio 1```. Note that here epoch is just 1000 iterations (not related to dataset size).
Q3:
How much higher? Not that it already take several days and 200GB of disk space for fashion. If you want you can modify cmd.py and change self.image_size
Q4:
Does not matter. Just specify directory you want using ```--checkpoints_dir```. Then when testing specify the checkpoint you want with --generator_checkpoint

**Comment by Seairis7** [comment]
@AliaksandrSiarohin  Even when I tried to train small data size the epoch time seems to be similar with large dataset size (i.e. around 4hrs each epoch) so what should i do so i can train a small set faster?? Is it related to no of iteration??

**Comment by AliaksandrSiarohin** [comment]
Yes as I previously mentioned each epoch here is just 1000 iterations, there is no dependence on number of samples. You can change it here https://github.com/AliaksandrSiarohin/pose-gan/blob/abda78780f5ef51092c154fd2ffe71fdeb41a693/pose_dataset.py#L58

**Comment by Seairis7** [comment]
@AliaksandrSiarohin  How to continue training from last saved checkpoint??

**Comment by AliaksandrSiarohin** [comment]
```
python train.py ... --generator_checkpoint /path/to/generator_cpk --discriminator_checkpoint /path/to/discriminator_cpk
```
... - stands for the options that you use before

**Comment by Seairis7** [comment]
@AliaksandrSiarohin  Suppose i have 1000 images to train  so what will be the ideal parameter value setup??
