### ISSUE TITLE
Parameters to enhance the training speed

### ISSUE THREAD

**Issue by gyawali9** [AliaksandrSiarohin/pose-gan#45]
what are the required parameters to be changed to train our self made data in an efficient way to enhance the accuracy as well?

**Comment by AliaksandrSiarohin** [comment]
Not clear, what you mean.

**Comment by gyawali9** [comment]
@AliaksandrSiarohin 
I tried to train 500 images with this code. Even for a single epoch it takes more training time. So,how to minimize the training time? What should be the value of parameters so that it will take less time to train my data?

**Comment by AliaksandrSiarohin** [comment]
This depends on your data. What is the resolution of your data? How many pairs you have? Single epoch here is simply 1000 iterations, you have the same? Slowe compared to what dataset market or fashion?

**Comment by gyawali9** [comment]
thank you sir

**Comment by gyawali9** [comment]
thank u sir
