### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by gyawali9** [AliaksandrSiarohin/pose-gan#47]
which model is created using baseline, dsc and  full??

**Comment by AliaksandrSiarohin** [comment]
Baseline - generator-no-warp.h5
DSC - generator-warp-mask.h5
FULL - generator-warp-mask-nn5-cl12.h5 (fashion),  generator-warp-mask-nn3-cl12.h5 (market)

**Comment by gyawali9** [comment]
thank u very very much sir,
