### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by samoyl11** [AliaksandrSiarohin/pose-gan#56]
@AliaksandrSiarohin, could you please give some information about the inference time?

**Comment by AliaksandrSiarohin** [comment]
I never measure it myself. Some people measure it. You can refer to this paper http://openaccess.thecvf.com/content_CVPR_2019/papers/Zhu_Progressive_Pose_Attention_Transfer_for_Person_Image_Generation_CVPR_2019_paper.pdf
table 2.

**Comment by samoyl11** [comment]
Dear Aliaksandr, 

Thank you for your reply! I also want to ask your permission for using your code in a programming competition. Thanks in advance!

Best, 
Alexander Samoylenko.

**Comment by AliaksandrSiarohin** [comment]
You can use the code in the way you want.
Regards, Aliaksandr Siarohin
