### ISSUE TITLE
IOError: Unable to open file (unable to open file: name = 'pose_estimator.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by sunshinewhy** [AliaksandrSiarohin/pose-gan#57]
when I run compute_coordinates.py, it shows the error:
Using TensorFlow backend.
Traceback (most recent call last):
model = load_model(args.pose_estimator)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = 'pose_estimator.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
How can I solve the error?Thanks!

**Comment by AliaksandrSiarohin** [comment]
Have you download pose estimator pose_estimator.h5 from https://yadi.sk/d/blgmGpDi3PjXvK

**Comment by sunshinewhy** [comment]
Excuse me, professor. I have download pose_estimator.h5, but when I run compute_coordinates.py, it shows:
OSError: [Errno 2] No such file or directory: './results/market_PATN/test_latest/images_crop/'
How can I solve this problem? Should I create a new file named images_crop?
Thank you!

**Comment by Shanmukh0028** [comment]
> when I run compute_coordinates.py, it shows the error: Using TensorFlow backend. Traceback (most recent call last): model = load_model(args.pose_estimator) File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper File "h5py/h5f.pyx", line 78, in h5py.h5f.open IOError: Unable to open file (unable to open file: name = 'pose_estimator.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0) How can I solve the error?Thanks!

@sunshinewhy did you get this error resolved, I am also facing same issue can you please tell me what have you done?
