### ISSUE TITLE
How to deal with missing joint?

### ISSUE THREAD

**Issue by chmxu** [AliaksandrSiarohin/pose-gan#60]
Thanks for the greate work! I want to know what if the human body has some missing joints? It seems the code restricts some joints to be valid. For example, when i don't have hip/shoulder joints, the function in https://github.com/AliaksandrSiarohin/pose-gan/blob/8693ec4b69fd3e83948bb1285c8e828fc62da390/pose_transform.py#L101 could raise KeyError.

**Comment by AliaksandrSiarohin** [comment]
Yes, the model assume that body is detected. You will not get any decent output from images like this, if you need some output inpaint missing joint with something, for example average location of this joint.

**Comment by chmxu** [comment]
I see. Thanks again.
