### ISSUE TITLE
File "create_pairs_dataset.py" missing

### ISSUE THREAD

**Issue by Lotayou** [AliaksandrSiarohin/pose-gan#7]
I've noticed that your instruction step 3 says "Create pairs dataset with` python create_pairs_dataset.py`. It define pairs for training." However, I cannot find any file with name `create_pairs_dataset.py` in your repository.

Could it be that you've changed the file name into `create_dataset_for_reid.py` or `create_pairs_for_reid.py`? And which one should I use to generate the training dataset? 

Thanks!

**Comment by AliaksandrSiarohin** [comment]
pull the latest version, I remove this file by accident.

**Comment by Lotayou** [comment]
I still cannot find the correct file on github webpage and executing `git pull` in bash command window just returns a message `Already up to date`. However I do find an `create_pairs_dataset.py` file in the `stn` branch, is it correct that I simply use this file? Thanks!

**Comment by AliaksandrSiarohin** [comment]
Yes, sorry. I was a bit busy with other staff. Now it is there.
