### ISSUE TITLE
Pytorch implementation

### ISSUE THREAD

**Issue by saurabhsharma1993** [AliaksandrSiarohin/pose-gan#9]
Hi,

I wrote a Pytorch implentation for this codebase. Please check it out . .
https://github.com/ssfootball04/pose-transfer/
Would be great if you can add a reference to this repo here :)

**Comment by AliaksandrSiarohin** [comment]
Hi, cool.
I add the reference.

**Comment by saurabhsharma1993** [comment]
Awesome
